In [1]:
import numpy as np

In [2]:
Y_train = np.load('data_decatur/processed/train/porosity.npy')
Y_test = np.load('data_decatur/processed/test/porosity.npy')

In [3]:
np.ravel(np.min(Y_train))

array([-0.01045141])

In [4]:
np.ravel(np.min(Y_test))

array([-0.0046579])

In [5]:
Y_test[Y_test<0] = 0.0001
Y_train[Y_train<0] = 0.0001

In [6]:
np.ravel(np.min(Y_test))

array([0.])

In [8]:
np.ravel(np.min(Y_train))

array([1.09616667e-05])